#Cross Validation
###Evualuating Model Performance

#####Cross Validation is a technique that allows us to choose which model is the best for the current scenerio.
- It allows us to evaluate a model performance

###Ways to train your model:
1. Use all available data for training and test on same data.
2. Split dataset into training and test sets
3. K fold Cross Validation

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

Here I am using three ML Models to check the accuracy. However, everytime we run the model it will give different score based on the train and test value becaue it is not uniform but changing constanly everytime we run it.

####Logistic Regression

In [ ]:
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)
model_lr.score(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9428571428571428

####Support Vector Machine

In [ ]:
model_svm = SVC()
model_svm.fit(X_train, y_train)
model_svm.score(X_train, y_train)

0.9619047619047619

####Random Forest

In [ ]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train, y_train)
model_rf.score(X_train, y_train)

1.0

###Dicision Tree

In [ ]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)
model_dt.score(X_train, y_train)

1.0

##Use K Fold

The data used in this example is a dummy data. We will use original Data in the next example.

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

####Stratified K Fold

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [ ]:
scores_lr = []
scores_svm = []
scores_rf = []
scores_dt = []

for train_index, test_index in kf.split(iris.data):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]

    scores_lr.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
    scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))

In [ ]:
scores_lr

[0.0, 0.0, 0.0]

In [ ]:
scores_svm

[0.0, 0.0, 0.0]

In [ ]:
scores_rf

[0.0, 0.0, 0.0]

In [ ]:
scores_dt

[0.0, 0.0, 0.0]

###Cross Val Score Method

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(LogisticRegression(), iris.data, iris.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [ ]:
cross_val_score(SVC(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [ ]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [ ]:
cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])