#Save model using Joblib and Pickle
- Load the model from a file into memory and use that to make actual predictions.

####How to solve Machine Learning Problems
- Forming a model involves two steps:
  1. Training a model using training dataset
  2. Ask your questions to the trained model that will give you the answer.

- The more dataset you have, your model gets more accurate.
- Once you trained your model, you don't have to trained it again.

###Use linear Regression Model

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
model_lr = linear_model.LinearRegression()

In [ ]:
model_lr.fit(df[['area']], df.price)

LinearRegression()

In [ ]:
model_lr.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

####Save Model using Python Picke

In [ ]:
import pickle

In [ ]:
with open('model_pickle', 'wb') as f:
  pickle.dump(model_lr, f)

Load Save Model

In [ ]:
with open('model_pickle', 'rb') as f:
  np = pickle.load(f)

In [ ]:
np.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

####Save model with Joblib
Joblib will be more efficient if your model consist of a large numpy array

In [ ]:
import joblib

In [ ]:
joblib.dump(model_lr, 'model_joblib')

['model_joblib']

Load model with Joblib

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])